### ISSUE TITLE
Crash with industrial_core source

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/industrial_core#132]
I've been using the `industrial_core` source without problem until last week; now the `industrial_robot_simulator` node systematically crashes like this;

```
[industrial_robot_simulator-2] process has died [pid 28201, exit code 127, cmd /home/dell/catkin_workspace/src/industrial_core/industrial_robot_simulator/industrial_robot_simulator __name:=industrial_robot_simulator __log:=/home/dell/.ros/log/50e913b0-c041-11e5-adcd-f01faf263c5d/industrial_robot_simulator-2.log].
log file: /home/dell/.ros/log/50e913b0-c041-11e5-adcd-f01faf263c5d/industrial_robot_simulator-2*.log
```

This is using the `indigo-devel` branch and the latest commit. If I remove the `industrial_core` source from my workspace (thus using the binaries provided from the repository) everything works well.

I did not manage to get logs nor backtrace of the crash at the moment. Here is what I have tried;
- Adding `output="screen"` in the [robot_interface_simulator.launch](https://github.com/ros-industrial/industrial_core/blob/indigo-devel/industrial_robot_simulator/launch/robot_interface_simulator.launch) node. It looks like:

``` xml
  <!-- industrial_robot_simulator: accepts robot commands and reports status -->
  <node pkg="industrial_robot_simulator" type="industrial_robot_simulator" name="industrial_robot_simulator" output="screen"/>

  <!-- joint_trajectory_action: provides actionlib interface for high-level robot control -->
  <node pkg="industrial_robot_client" type="joint_trajectory_action" name="joint_trajectory_action" output="screen"/>
```
- Set `CMAKE_BUILD_TYPE`  to `Debug` for the whole catkin workspace. Add `launch-prefix="gdb -ex run --args"` in the launch files. It looks like:

``` xml
  <!-- industrial_robot_simulator: accepts robot commands and reports status -->
  <node pkg="industrial_robot_simulator" type="industrial_robot_simulator" name="industrial_robot_simulator" output="screen" launch-prefix="gdb -ex run --args"/>

  <!-- joint_trajectory_action: provides actionlib interface for high-level robot control -->
  <node pkg="industrial_robot_client" type="joint_trajectory_action" name="joint_trajectory_action" output="screen" launch-prefix="gdb -ex run --args"/>
```

But it doesn't work as expected:

```
Type "apropos word" to search for commands related to "word"...
"/home/dell/catkin_workspace/src/industrial_core/industrial_robot_simulator/industrial_robot_simulator": not in executable format: File format not recognized
Starting program:  __name:=industrial_robot_simulator __log:=/home/dell/.ros/log/4e112638-c045-11e5-9d5f-f01faf263c5d/industrial_robot_simulator-2.log
No executable file specified.
Use the "file" or "exec-file" command.
```

I have reproduced this bug on 3 other machines, another machine is not affected.

**Comment by gavanderhoorn** [comment]
re: `launch-prefix` with gdb doesn't work: you cannot use that for Python scripts directly like that. In any case, you'd be debugging a `python` instance, not the script itself.

Also: what is the output when running it with `output=screen`?

**Comment by VictorLamoine** [comment]
I'll try with `pdb`, `output=screen` still produces empty logs.

**Comment by gavanderhoorn** [comment]
Also:
1. does it crash immediately, or only after some use?
2. make sure `robot_interface_simulator.launch` is actually being used: I've seen launch files directly start the nodes instead of including that file
3. `output=screen` does not go to the logs, that's the point. There is no output in your terminal at all?

**Comment by gavanderhoorn** [comment]
You can also always use `roslaunch --screen ..` to force all nodes to output to the screen, without having to edit any files.

**Comment by gavanderhoorn** [comment]
Exit code `127` generally means something like 'command not found'.

Can you check you have `/usr/bin/env` on the machines where it crashes? Also, which version of Python are you running? And what is the output of `/usr/bin/env python` on the crashing machines?

**Comment by VictorLamoine** [comment]
1. It crashes immediately.
2. I'll check that.
3. The terminal output, not the log files sorry!

``` bash
$ roslaunch --screen fanuc_motion cube.launch 
... logging to /home/dell/.ros/log/3f2d8394-c047-11e5-b973-f01faf263c5d/roslaunch-M6700-29527.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://M6700:52991/

SUMMARY
========

PARAMETERS
 * /controller_joint_names: ['joint_1', 'join...
 * /move_group/allow_trajectory_execution: True
 * /move_group/allowed_execution_duration_scaling: 1.2
 * /move_group/allowed_goal_duration_margin: 0.5
 * /move_group/capabilities: move_group/MoveGr...
 * /move_group/controller_list: [{'action_ns': 'j...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/manipulator/longest_valid_segment_fraction: 0.05
 * /move_group/manipulator/planner_configs: ['SBLkConfigDefau...
 * /move_group/manipulator/projection_evaluator: joints(joint_1,jo...
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_simple_con...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
 * /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
 * /move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/SBLkConfigDefault/range: 0.0
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
 * /move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
 * /move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
 * /move_group/planner_configs/TRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/execution_duration_monitoring: False
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/manipulator/kinematics_solver: fanuc_m10ia_manip...
 * /robot_description_kinematics/manipulator/kinematics_solver_attempts: 3
 * /robot_description_kinematics/manipulator/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/manipulator/kinematics_solver_timeout: 0.005
 * /robot_description_planning/joint_limits/joint_1/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_1/max_acceleration: 0.734
 * /robot_description_planning/joint_limits/joint_1/max_velocity: 3.67
 * /robot_description_planning/joint_limits/joint_2/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_2/max_acceleration: 0.664
 * /robot_description_planning/joint_limits/joint_2/max_velocity: 3.32
 * /robot_description_planning/joint_limits/joint_3/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_3/max_acceleration: 0.734
 * /robot_description_planning/joint_limits/joint_3/max_velocity: 3.67
 * /robot_description_planning/joint_limits/joint_4/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_4/max_acceleration: 1.396
 * /robot_description_planning/joint_limits/joint_4/max_velocity: 6.98
 * /robot_description_planning/joint_limits/joint_5/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_5/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_5/max_acceleration: 1.396
 * /robot_description_planning/joint_limits/joint_5/max_velocity: 6.98
 * /robot_description_planning/joint_limits/joint_6/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_6/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_6/max_acceleration: 2.094
 * /robot_description_planning/joint_limits/joint_6/max_velocity: 10.47
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: indigo
 * /rosversion: 1.11.16

NODES
  /
    cube (fanuc_motion/cube)
    industrial_robot_simulator (industrial_robot_simulator/industrial_robot_simulator)
    joint_trajectory_action (industrial_robot_client/joint_trajectory_action)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [29542]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 3f2d8394-c047-11e5-b973-f01faf263c5d
process[rosout-1]: started with pid [29555]
started core service [/rosout]
process[industrial_robot_simulator-2]: started with pid [29572]
: Aucun fichier ou dossier de ce type
process[joint_trajectory_action-3]: started with pid [29573]
process[robot_state_publisher-4]: started with pid [29574]
process[move_group-5]: started with pid [29575]
[ INFO] [1453384797.027699998]: Adding joint_1 to list parameter
[ INFO] [1453384797.027795190]: Adding joint_2 to list parameter
[ INFO] [1453384797.027829718]: Adding joint_3 to list parameter
[ INFO] [1453384797.027859558]: Adding joint_4 to list parameter
[ INFO] [1453384797.027893869]: Adding joint_5 to list parameter
[ INFO] [1453384797.027925298]: Adding joint_6 to list parameter
[ INFO] [1453384797.028007438]: Found user-specified joint names in 'controller_joint_names': [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
[ INFO] [1453384797.028055727]: Filtered joint names to 6 joints
process[cube-6]: started with pid [29586]
[industrial_robot_simulator-2] process has died [pid 29572, exit code 127, cmd /home/dell/MEGAsync/catkin_workspace/src/industrial_core/industrial_robot_simulator/industrial_robot_simulator __name:=industrial_robot_simulator __log:=/home/dell/.ros/log/3f2d8394-c047-11e5-b973-f01faf263c5d/industrial_robot_simulator-2.log].
log file: /home/dell/.ros/log/3f2d8394-c047-11e5-b973-f01faf263c5d/industrial_robot_simulator-2*.log
process[rviz-7]: started with pid [29600]
[ INFO] [1453384797.093605988]: Loading robot model 'fanuc_m10ia'...
[ INFO] [1453384797.108045770]: Loading robot model 'fanuc_m10ia'...
[ INFO] [1453384797.118190732]: rviz version 1.11.10
[ INFO] [1453384797.118248168]: compiled against OGRE version 1.8.1 (Byatis)
[ INFO] [1453384797.240100829]: Stereo is NOT SUPPORTED
[ INFO] [1453384797.240190175]: OpenGl version: 3 (GLSL 1.3).
[ INFO] [1453384797.300093454]: joint_1 -0.78 0.78 1
[ INFO] [1453384797.300138061]: joint_2 -1.57 1.57 1
[ INFO] [1453384797.300156201]: joint_3 -3.14 4.61 1
[ INFO] [1453384797.300173786]: joint_4 -1.57 1.57 1
[ INFO] [1453384797.300192402]: joint_5 -2.41 2.44 1
[ INFO] [1453384797.300209214]: joint_6 -4.71 4.71 1
[ INFO] [1453384797.313872872]: joint_1 -0.78 0.78 1
[ INFO] [1453384797.313907060]: joint_2 -1.57 1.57 1
[ INFO] [1453384797.313919899]: joint_3 -3.14 4.61 1
[ INFO] [1453384797.313932758]: joint_4 -1.57 1.57 1
[ INFO] [1453384797.313944215]: joint_5 -2.41 2.44 1
[ INFO] [1453384797.313956428]: joint_6 -4.71 4.71 1
[ INFO] [1453384797.350115571]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1453384797.352749612]: MoveGroup debug mode is OFF
Starting context monitors...
[ INFO] [1453384797.352791734]: Starting scene monitor
[ INFO] [1453384797.355372396]: Listening to '/planning_scene'
[ INFO] [1453384797.355407348]: Starting world geometry monitor
[ INFO] [1453384797.357895662]: Listening to '/collision_object' using message notifier with target frame '/base_link '
[ INFO] [1453384797.360825715]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1453384797.380332251]: Listening to '/attached_collision_object' for attached collision objects
Context monitors started.
[ INFO] [1453384797.454112565]: Initializing OMPL interface using ROS parameters
[ INFO] [1453384797.475680064]: Using planning interface 'OMPL'
[ INFO] [1453384797.535007075]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1453384797.535618786]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1453384797.536148277]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1453384797.536700941]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1453384797.537121107]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1453384797.537580299]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1453384797.537621541]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1453384797.537641332]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1453384797.537657313]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1453384797.537672984]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1453384797.537689637]: Using planning request adapter 'Fix Start State Path Constraints'
[ INFO] [1453384797.871543030]: MoveitSimpleControllerManager: Added FollowJointTrajectory controller for 
[ INFO] [1453384797.871705805]: Returned 1 controllers in list
[ INFO] [1453384797.885521704]: Trajectory execution is managing controllers
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
[ INFO] [1453384798.040532663]: 

********************************************************
* MoveGroup using: 
*     - CartesianPathService
*     - ExecutePathService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
*     - GetPlanningSceneService
*     - ExecutePathService
********************************************************

[ INFO] [1453384798.040619073]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1453384798.040642365]: MoveGroup context initialization complete

All is well! Everyone is happy! You can start planning now!

[ WARN] [1453384798.045434667]: Trajectory state not received for 1.000000 seconds
[ INFO] [1453384798.776421633]: Ready to take MoveGroup commands for group manipulator.
[ WARN] [1453384798.776511682]: Start ExecuteKnownTrajectory trajectory
[ INFO] [1453384798.777897534]: Received request to compute Cartesian path
[ INFO] [1453384798.778255789]: Attempting to follow 5 waypoints for link 'tool0' using a step of 0.050000 m and jump threshold 0.000000 (in global reference frame)
[ INFO] [1453384798.783766992]: Computed Cartesian path with 29 points (followed 100.000000% of requested trajectory)
[ INFO] [1453384798.785287396]: Received new trajectory execution service request...
[ INFO] [1453384798.785715059]: Received new goal
[ERROR] [1453384798.785742507]: Joint trajectory action rejected: waiting for (initial) feedback from controller
[ WARN] [1453384798.786000173]: Controller  failed with error code INVALID_GOAL
[ WARN] [1453384798.786090171]: Controller handle  reports status FAILED
[ INFO] [1453384798.786182496]: Execution completed: FAILED
[ INFO] [1453384802.795774829]: Received request to compute Cartesian path
[ INFO] [1453384802.796007109]: Attempting to follow 5 waypoints for link 'tool0' using a step of 0.050000 m and jump threshold 0.000000 (in global reference frame)
[ INFO] [1453384802.811346079]: Computed Cartesian path with 30 points (followed 100.000000% of requested trajectory)
[ INFO] [1453384802.814834149]: Received new trajectory execution service request...
[ INFO] [1453384802.815794128]: Received new goal
[ERROR] [1453384802.815867554]: Joint trajectory action rejected: waiting for (initial) feedback from controller
[ WARN] [1453384802.816216028]: Controller  failed with error code INVALID_GOAL
[ WARN] [1453384802.816326724]: Controller handle  reports status FAILED
[ INFO] [1453384802.816654563]: Execution completed: FAILED
terminate called after throwing an instance of 'class_loader::LibraryUnloadException'
  what():  Attempt to unload library that class_loader is unaware of.
================================================================================REQUIRED process [cube-6] has died!
process has died [pid 29586, exit code -6, cmd /home/dell/MEGAsync/catkin_workspace/devel/lib/fanuc_motion/cube __name:=cube __log:=/home/dell/.ros/log/3f2d8394-c047-11e5-b973-f01faf263c5d/cube-6.log].
log file: /home/dell/.ros/log/3f2d8394-c047-11e5-b973-f01faf263c5d/cube-6*.log
Initiating shutdown!
================================================================================
[cube-6] killing on exit
[rviz-7] killing on exit
[move_group-5] killing on exit
[robot_state_publisher-4] killing on exit
[joint_trajectory_action-3] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

```
XDG_VTNR=7
XDG_SESSION_ID=c3
CLUTTER_IM_MODULE=xim
SELINUX_INIT=YES
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/dell
SESSION=ubuntu
GPG_AGENT_INFO=/run/user/1000/keyring-yNsSg4/gpg:0:1
TERM=xterm
SHELL=/bin/bash
VTE_VERSION=3409
XDG_MENU_PREFIX=gnome-
ROS_ROOT=/opt/ros/indigo/share/ros
ROS_PACKAGE_PATH=/home/dell/MEGAsync/catkin_workspace/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks
ROS_MASTER_URI=http://localhost:11311
WINDOWID=29360139
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/3479
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-yNsSg4
GTK_MODULES=overlay-scrollbar:unity-gtk-module
USER=dell
LD_LIBRARY_PATH=/home/dell/MEGAsync/catkin_workspace/devel/lib:/home/dell/MEGAsync/catkin_workspace/devel/lib/x86_64-linux-gnu:/opt/ros/indigo/lib/x86_64-linux-gnu:/opt/ros/indigo/lib
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
CPATH=/home/dell/MEGAsync/catkin_workspace/devel/include:/opt/ros/indigo/include
SSH_AUTH_SOCK=/run/user/1000/keyring-yNsSg4/ssh
CXXFLAGS=-fdiagnostics-color 
SESSION_MANAGER=local/M6700:@/tmp/.ICE-unix/3661,unix/M6700:/tmp/.ICE-unix/3661
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
PATH=/home/dell/MEGAsync/catkin_workspace/devel/bin:/opt/ros/indigo/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
DESKTOP_SESSION=ubuntu
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=appmenu-qt5
PWD=/home/dell
JOB=dbus
XMODIFIERS=@im=ibus
GNOME_KEYRING_PID=3477
LANG=fr_FR.UTF-8
GDM_LANG=fr_FR
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
IM_CONFIG_PHASE=1
COMPIZ_CONFIG_PROFILE=ubuntu
ROSLISP_PACKAGE_DIRECTORIES=/home/dell/MEGAsync/catkin_workspace/devel/share/common-lisp
CYUSB_ROOT=/home/dell/libraries/cyusb_linux_nit
GDMSESSION=ubuntu
SESSIONTYPE=gnome-session
XDG_SEAT=seat0
HOME=/home/dell
SHLVL=1
ROS_DISTRO=indigo
LANGUAGE=fr_FR
ENSENSO_INSTALL=/opt/ensenso
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
PYTHONPATH=/home/dell/MEGAsync/catkin_workspace/devel/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages
LOGNAME=dell
COMPIZ_BIN_PATH=/usr/bin/
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/
QT4_IM_MODULE=xim
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-90Z9stwzST
PKG_CONFIG_PATH=/home/dell/MEGAsync/catkin_workspace/devel/lib/pkgconfig:/home/dell/MEGAsync/catkin_workspace/devel/lib/x86_64-linux-gnu/pkgconfig:/opt/ros/indigo/lib/x86_64-linux-gnu/pkgconfig:/opt/ros/indigo/lib/pkgconfig
LESSOPEN=| /usr/bin/lesspipe %s
INSTANCE=
TEXTDOMAIN=im-config
CMAKE_PREFIX_PATH=/home/dell/MEGAsync/catkin_workspace/devel:/opt/ros/indigo
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
XDG_CURRENT_DESKTOP=Unity
GTK_IM_MODULE=ibus
LESSCLOSE=/usr/bin/lesspipe %s %s
TEXTDOMAINDIR=/usr/share/locale/
ROS_ETC_DIR=/opt/ros/indigo/etc/ros
COLORTERM=gnome-terminal
XAUTHORITY=/home/dell/.Xauthority
_=/usr/bin/env
```

```
$ /usr/bin/env python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by gavanderhoorn** [comment]
```
: Aucun fichier ou dossier de ce type
```

Seems to point to some issue.

Seeing all the `MEGAsync` references: are you syncing your workspace to a Windows computer as well by any chance? Could you check the line-endings of the `industrial_robot_simulator` script?

And if you start `robot_interface_simulator.launch` by itself, it also crashes?

**Comment by VictorLamoine** [comment]
Looks like a nasty character in one of the files!!

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/dell/MEGAsync/catkin_workspace/devel/lib/industrial_robot_client/joint_trajectory_action", line 1
SyntaxError: Non-ASCII character '\x80' in file /home/dell/MEGAsync/catkin_workspace/devel/lib/industrial_robot_client/joint_trajectory_action on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> <string>(1)<module>()
(Pdb) 

```

I can reproduce the problem outside MEGAsync so it's probably not the source of the problem (I doubled check that there is no diff in `industrial_core` source).

**Comment by gavanderhoorn** [comment]
Well, I'm inclined to believe it's something local to your setup(s), as that particular file hasn't seen any changes since 2015-01-16 ([history](https://github.com/ros-industrial/industrial_core/commits/indigo-devel/industrial_robot_simulator/industrial_robot_simulator)).

`0x80` is indeed not in ASCII range, so the error message is correct. Just where that character is coming from then is hard to understand.

**Comment by VictorLamoine** [comment]
My git policy regarding CRLF was set to true (`git config --global core.autocrlf true`), I think this is what caused the problem.

Switching to `git config --global core.autocrlf input`, removing the workspace and configure/compiling agains solves the problem.

I'm not 100% sure because I'm not able to reproduce the bug again by switching to `true` again... :smile:

**Comment by gavanderhoorn** [comment]
Ok, thanks for reporting back.

Good to hear you solved it.

**Comment by gavanderhoorn** [comment]
And just to clarify: this is a client-side configuration option. The sources in the repository are ok.
